"""empty message

Revision ID: 4c6f42a59cf2
Revises: a9506268ffee
Create Date: 2023-08-15 01:48:09.988435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6f42a59cf2'
down_revision = 'a9506268ffee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('surface_water',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
