"""empty message

Revision ID: 81ff558ee0f9
Revises: 4c6f42a59cf2
Create Date: 2023-08-15 02:28:12.122685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ff558ee0f9'
down_revision = '4c6f42a59cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
