"""empty message

Revision ID: b3d807d5ad28
Revises: 4c83a2d87398
Create Date: 2023-08-14 13:06:08.887789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d807d5ad28'
down_revision = '4c83a2d87398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('eyes_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eyes_color', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
